services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: subscriptions-app:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=subscriptions
      - PORT=8080
      - DATABASE_URL=jdbc:postgresql://db:5432/subscriptions_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=0000
      - SPRING_LIQUIBASE_ENABLED=true

    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres
    container_name: postgres_subscr_db
    environment:
      - POSTGRES_DB=subscriptions_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network


volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
